# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b81ee28bb971755ac06b715665a270bd"
application_url = "https://b5fb-12-31-100-34.ngrok-free.app"
embedded = true
name = "Getz's Apps"
handle = "GetzsApps"

[build]
include_config_on_deploy = true
dev_store_url = "restockertest.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory, write_assigned_fulfillment_orders, write_merchant_managed_fulfillment_orders, write_draft_orders,write_order_edits, write_payment_terms, write_orders, read_customers, read_inventory, read_locations, read_orders, read_products, write_products, read_product_listings"

[auth]
redirect_urls = [
  "https://b5fb-12-31-100-34.ngrok-free.app/auth/callback",
  "https://b5fb-12-31-100-34.ngrok-free.app/auth/shopify/callback",
  "https://b5fb-12-31-100-34.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = true
