# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5bf13b7310436f71c3b049a5cee818ea"
application_url = "https://nick.getzs.com/"
embedded = true
name = "Getzs-Apps"
handle = "getzs-apps"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders, write_payment_terms, write_orders, read_customers, read_inventory, read_locations, read_orders, read_products, write_products, read_product_listings"

[auth]
redirect_urls = [
  "https://nick.getzs.com/auth/callback",
  "https://nick.getzs.com/auth/shopify/callback",
  "https://nick.getzs.com/api/auth/callback"
]

[pos]
embedded = true

[build]
dev_store_url = "test-getzs.myshopify.com"
automatically_update_urls_on_dev = true
